---
kind: Deployment
apiVersion: aaps/v1
metadata:
    name: my-deployment
spec: 
    replicas: 2
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: my-app
    template:
        metadata:
            name: my-pod
            labels:
                app: my-app
        spec:
            containers:
            - image: aadil1142/myimage:latest
              name: mycontainer
              ports:
              - containerPort: 8501
...
---
kind: Service
apiVersion: v1
metadata: 
    name: my-service
spec:
    type: NodePort
    selector:
        app: my-app
    ports:
    - port: 80
      targetPort: 8501
      nodePort: 30001
...